//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLinq.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EntityFrameworkLinq.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT p.product_id, t.product_title, t.product_category_id, m.manufacturer_name, p.unit_price, c.category_name FROM shop_products AS p INNER JOIN product_titles AS t ON t.product_title_id = p.product_title_id INNER JOIN product_manufacturers AS m ON m.manufacturer_id = p.product_manufacturer_id INNER JOIN product_categories AS c ON c.category_id = t.product_category_id ORDER BY t.product_title.
        /// </summary>
        internal static string GetFullProductReport {
            get {
                return ResourceManager.GetString("GetFullProductReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT p.product_id, t.product_title, m.manufacturer_name, p.unit_price FROM shop_products AS p INNER JOIN product_titles AS t ON t.product_title_id = p.product_title_id INNER JOIN product_manufacturers AS m ON m.manufacturer_id = p.product_manufacturer_id ORDER BY t.product_title DESC.
        /// </summary>
        internal static string GetProductReport {
            get {
                return ResourceManager.GetString("GetProductReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT category_id, category_name FROM product_categories ORDER BY category_name.
        /// </summary>
        internal static string GetReportCategoriesReport {
            get {
                return ResourceManager.GetString("GetReportCategoriesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE location_city (city_id INTEGER PRIMARY KEY AUTOINCREMENT, city TEXT NOT NULL, country TEXT NOT NULL)
        ///INSERT INTO location_city VALUES (1, &apos;Kyiv&apos;, &apos;Ukraine&apos;)
        ///INSERT INTO location_city VALUES (2, &apos;Vinnitsya&apos;, &apos;Ukraine&apos;)
        ///INSERT INTO location_city VALUES (3, &apos;Kharkiv&apos;, &apos;Ukraine&apos;)
        ///INSERT INTO location_city VALUES (4, &apos;London&apos;, &apos;United Kingdom&apos;)
        ///INSERT INTO location_city VALUES (5, &apos;Lviv&apos;, &apos;Ukraine&apos;)
        ///
        ///CREATE TABLE locations (location_id INTEGER PRIMARY KEY AUTOINCREMENT, location_address TEXT  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InitializationScript {
            get {
                return ResourceManager.GetString("InitializationScript", resourceCulture);
            }
        }
    }
}
